### PR TITLE
minor github links fixing

### PR DESCRIPTION
**Pull request by j1nxie**
fixing some github links in the footer and the documentations to correctly point to the monorepo.

very minor fixes, i'll go through all the text files another time to see if i missed anything else.

### CODE REVIEW

**Comment by zkldi** [comment]
Any reason this is a draft?

**Comment by j1nxie** [comment]
main reason this is a draft is because i haven't looked fully into the links and i don't really want them dangling.

i'll finalize this in a few hrs, shouldn't take too long to look through all the documentations files.

**Comment by zkldi** [comment]
looks good to me! Is this finalised?

**Comment by j1nxie** [comment]
i think that's everything, yeah, can't seem to find any other references to github links. if i do find any i'll open another PR, but this is good for now!

**Pull request merged**
