### PR TITLE
feat: arcaea support

### PR DESCRIPTION
**Pull request by j1nxie**
arcaea support for tachi!

marked as a draft PR until we figure out the seeds and import methods. currently waiting on arcaea 5.0 to release to get the latest seeds.

### CODE REVIEW

**Comment by j1nxie** [comment]
marking this as ready for review

@beerpiss should have a very basic way of pulling data from the game readily available

**Comment by zkldi** [comment]
this'll go on bokutachi jsyk

**Comment by j1nxie** [comment]
actually i'm rather interested on why, because arcaea by itself is very similar to the arcade rhythm games available on kamaitachi

i don't have a problem with it being on either instances though

**Comment by zkldi** [comment]
bokutachi is for games you can play at home and kamaitachi is for arcade games

**Comment by j1nxie** [comment]
sounds good to me honestly

**Comment by zkldi** [comment]
will review later this week

**Comment by zkldi** [comment]
will be on staging for you guys to test it thoroughly

**Pull request merged**
