### PR TITLE
Added announced June Infinitas unlocks

### PR DESCRIPTION
**Pull request by justOkapi**
Holic in Infinitas is proof Konami loves me and wants me to be happy.

ヒマワリ is cool too I guess.

### CODE REVIEW

**Comment by zkldi** [comment]
whats happening with the gitignore here? if this script is in `rerunners` it should be published in the repo.

**Comment by justOkapi** [comment]
Literally the only thing that changes in my script is the songID, it's unnecessary for it to be updated every time I update the monthlies.

**Comment by justOkapi** [comment]
And I *think* my script is already in the main staging branch.

**Comment by justOkapi** [comment]
Confirmed my script is in the main staging branch already, added some commentary on how it works in case someone else wants to take a stab at it.

**Comment by zkldi** [comment]
ah right makes sense. seems fair that this is untracked. simpler than making this script take command line args.

**Pull request merged**
