### PR TITLE
update sdvx konaste charts and tierlist

### PR DESCRIPTION
**Pull request by cg505**

### CODE REVIEW

**Comment by cg505** [comment]
Fixed seed comparison link https://bokutachi.xyz/utils/seeds?repo=GitHub%3ATNG-dev%2FTachi&sha=643fbb1ed9d123c2c850e2684fdf3ea48a107858&compareRepo=GitHub%3Acg505%2FTachi&compareSHA=2e837fe6045e4ee6ea6069273406fe0e6caff7a7

**Comment by zkldi** [comment]
not urlsafe i guess? thanks bot

**Comment by zkldi** [comment]
lgtm

**Comment by zkldi** [comment]
backported

**Comment by cg505** [comment]
link issues are recorded/explained in #help-bugs

**Pull request merged**
