### PR TITLE
updated IIDX DBs for new Infinitas pack

### PR DESCRIPTION
**Pull request by justOkapi**
please stop marking my posts as transgender

### CODE REVIEW

**Comment by zkldi** [comment]
these are failing tests, i can't merge this until the tests pass, please look into why they're failing.
image

**Comment by justOkapi** [comment]
Yeah I'm doing that now, I blame your script

**Comment by justOkapi** [comment]
Good now

**Comment by zkldi** [comment]
yup, all looks good to me. Thank you.

**Pull request merged**
