### PR TITLE
Added IIDX Infinitas : Bistrover Vol.2 [Vol.22] support list

### PR DESCRIPTION
**Pull request by kawachiboy14**
Added IIDX Infinitas : Bistrover Vol.2 [Vol.22] support list but I don't check the past song before that. 

- [x] 2024 January songs support
- [x] 2023 December songs support
- [x] 2023 November songs support

### CODE REVIEW

**Comment by zkldi** [comment]
Hi, is this ready to be looked at, or does `2024 January songs support/2023 December songs support` need to be finished first?

**Comment by kawachiboy14** [comment]
> Hi, is this ready to be looked at, or does `2024 January songs support/2023 December songs support` need to be finished first?

I finished both + KAC now. It's ready to check.

(Sorry, I never used GitHub before. I'm old tech.)

**Comment by zkldi** [comment]
> I finished both + KAC now. It's ready to check.
> 
> (Sorry, I never used GitHub before. I'm old tech.)

It's OK! Thank you for the PR.

In the future if something isn't ready to be checked, [mark it as a draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft).

Otherwise, I'll check it and might merge it before it's ready!

**Comment by GRIM657** [comment]
Hey! Sorry I didn't notice this PR, or I would have contributed here instead.

**Comment by kawachiboy14** [comment]
> Hey! Sorry I didn't notice this PR, or I would have contributed here instead.

It's all good. I check your code and it is better than mine. I will close this pull.

**Pull request closed without merging**
