### PR TITLE
Buncha Infinitas stuff

### PR DESCRIPTION
**Pull request by justOkapi**

### CODE REVIEW

**Comment by justOkapi** [comment]
Thank [insert favorite higher power here] for the the DB manager

**Comment by zkldi** [comment]
i'm the higher power here

**Comment by zkldi** [comment]
i wonder why the bot doesn't re-comment when another subsequent change alters the seeds. it really should.

**Comment by justOkapi** [comment]
> i wonder why the bot doesn't re-comment when another subsequent change alters the seeds. it really should.

it's your code my guy

**Pull request merged**
