### PR TITLE
dashboard & GPT navbar padding

### PR DESCRIPTION
**Pull request by saintnoodle**
remove row from class name since .row adjusts padding by -12.5px and causes navbar content to extend beyond the card

### CODE REVIEW

**Comment by zkldi** [comment]
is this ready to merge?

**Comment by saintnoodle** [comment]
I have no other changes to make to this branch so other than that conflict it should be ready to go

**Comment by saintnoodle** [comment]
i obviously don't understand how conflicts work. whatever.

**Comment by zkldi** [comment]
i hate githubs way of doing merge resolves lol. Merge branch 'staging' into dev my ass.

**Comment by zkldi** [comment]
luckily none of this matters anymore as I'm just squashing.

**Pull request merged**
