### PR TITLE
sdvx charts 2023021400

### PR DESCRIPTION
**Pull request by saintnoodle**

### CODE REVIEW

**Comment by zkldi** [comment]
Is this ready for merge? You mentioned that there were more changes that needed to be done? If not, mark this as ready for review and i'll get back to it tonight.

**Comment by saintnoodle** [comment]
The changes I want to make are to do with searchTerms, this request is just to get the database updated with the new content ASAP. Updating the searchTerms will take a while as I still have to decide what information I want and need in there. redundant terms (single word titles/artists) can be safely removed meanwhile some songs like those with japanese titles will probably require several redundant terms to be fully searchable.

**Comment by saintnoodle** [comment]
I don't need to change anything else...

**Comment by zkldi** [comment]
all looks good to me. thank you!!

**Pull request merged**
