### PR TITLE
Jubeat db mistake corrections nonfinal.

### PR DESCRIPTION
**Pull request by Mobiuslau**
Fixes issue #619.

The following mistakes were found in the Jubeat database-seeds:

* Song `Glorious days` misspelled as `Glorius days`.
* Song `ユメイロコンバス` misspelled as `ユメイロコンパス`.
* Song `紅蓮華` has wrong artist tag.
* Previously added Festo charts did not have decimal difficulties for `9.x` and `10.x`.
* Chart difficulty updates were previously not considered.

### CODE REVIEW

**Comment by zkldi** [comment]
nonfinal?

**Comment by Mobiuslau** [comment]
With onfinal I mean that newer Festo charts have not been added yet. I first wanted to fix these mistakes.

**Comment by zkldi** [comment]
Oh right, okay. Reviewing the PR now then.

**Comment by zkldi** [comment]
anyway, PR looks good to me - The lack of decimals on some charts should be considered deliberate as some of the charts in the database never got decimal levels. (i.e. didn't make it to festo)

**Pull request merged**
