### PR TITLE
new Infinitas pack + monthlies

### PR DESCRIPTION
**Pull request by justOkapi**
Lots of songs to add.  Sorry for the delay, been a rough few weeks.

### CODE REVIEW

**Comment by justOkapi** [comment]
Estella is missing from the adds.  I'm investigating, but it looks like there's something fucky with some of the 5th Style ingameIDs?

**Comment by justOkapi** [comment]
Yeah there's a few 5th Style songs that have inGameIDs with format 52xx and I'm pretty sure that's not right but I want to double check that I'm not missing something so I'm waiting on input from anyone else who may have had their fingers in this honey pot.  Once I have a better idea what the hell this is all about I'll get that fixed and add Estella as well.

**Comment by justOkapi** [comment]
JK it is right, these are old songs from prior to the current inGameID schema.  Added Estella's new inGameID and we're off to the races.

**Comment by zkldi** [comment]
old omnimix stuff starts a lot of its CS ports at 5200, and non-cs stuff at 5100. iirc

**Comment by zkldi** [comment]
all looks good to me. thanks!

**Pull request merged**
