### PR TITLE
[chunithm] SUN+ and SUN Omnimix support, split into International and JP versions

### PR DESCRIPTION
**Pull request by beerpiss**
## Changes
- Split versions into separate regions. This was done because each region has their own release schedule, and sometimes songs would release in International first (WACCA collab, HARDCORE TANO*C collab).
- Properly mark 5 songs (LAMIA, 雷切-RAIKIRI-, フリーフォール, Invisible Frenzy, Quon) as from versions SUN International **and** SUN PLUS
- Added all SUN PLUS songs to date
- Added all SUN PLUS International songs (including the new TANO*C collab)

## Todo
- [x] Find all the omnimix opts to import (Done: ANEW, A114, ASAN, ASUN)
- [x] Difficulty folders (BASIC, ADVANCED, EXPERT, MASTER, ULTIMA)

### CODE REVIEW

**Comment by beerpiss** [comment]
Marking as draft in anticipation for new content tomorrow (King of Performai qualifiers).

**Comment by beerpiss** [comment]
Undrafting because the KoP qualifier (and the bonus song) comes on 2/11, not yesterday like I initially thought.

**Comment by zkldi** [comment]
why does the tachi-repo-bot sometimes double comment and sometimes not comment at all. there are clearly relevant changes on this PR. @tachi-repo-bot please do your job

**Comment by zkldi** [comment]
merging even with errors so that it can fail gracefully on staging. it's a flakey test that's been flakey for nearly a year and i've finally gotten around to maybe fixing it. It's a JS async issue. good fun.

**Pull request merged**
